name: Ubuntu

on: [push]

jobs:
  build-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]

    steps:
    - uses: actions/checkout@v4
    - name: build-example
      run: |
        cmake -DTINYCOLORMAP_BUILD_TOOLS=ON .
        make
    - name: ctest
      run: ctest
